"""Dialogues du taxi (v6) -> ../godot/data/taxi.json. Toutes les répliques sont dites à voix haute (build_voix.py).

Une intervention du client = un fil de trois échanges : il dit quelque chose, le joueur répond sur un ton
(chaleureux, drôle, curieux, sobre ; ou se tait), le client réagit selon ses goûts cachés, puis le fil continue.
Indices : l'allure du client (affichée sous son nom), ses réactions, et ses réponses quand on lui pose des questions
(« Qu'est-ce qui vous fait plaisir ? »…). Variables : {prenom} {metier} {metier_detail} {loisir} {animal} {famille}
{commune} {dest} {dest_commune} ; {e} = accord au féminin (client), {masculin|féminin} pour les autres accords. Les répliques du joueur n'ont pas de variable."""
import json, os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "godot", "data", "taxi.json")
TONS = ["chaleureux", "drole", "curieux", "sobre"]

# ---------------------------------------------------------------- caractères
CARACTERES = [
    dict(id="jovial", nom="jovial", bavard=0.9,
         gouts=dict(chaleureux=1, drole=2, curieux=1, sobre=-1, silence=-2),
         allure=["{Il|Elle} sourit jusqu'aux oreilles.", "{Il|Elle} fredonne en s'installant.", "{Il|Elle} a l'air d'excellente humeur."],
         bien=["Ha ha ! Vous me plaisez, vous !", "Ah, ça c'est envoyé !", "Hé hé, j'adore.", "Vous êtes impayable !",
               "Ha ! Je la ressortirai, celle-là.", "On va bien s'entendre, tous les deux.", "Voilà un chauffeur qui a de l'humour !",
               "Ah, ça fait du bien de rigoler un peu.", "Vous, vous avez le sens de la répartie !", "Excellent, excellent !",
               "Je sens que la course va passer vite.", "Ha ha, arrêtez, j'ai mal aux côtes !"],
         moyen=["Ouais, ouais.", "Bon, bon…", "Si vous le dites !", "Ah. D'accord.", "Mouais.", "Hm, pourquoi pas.",
                "C'est vous qui voyez.", "Bon, passons."],
         mal=["Vous êtes pas drôle, vous, hein…", "Bon. Ambiance.", "Ouh là, quel enthousiasme…", "Allez, déridez-vous un peu !",
              "C'est un taxi ou un corbillard, ici ?", "Vous avez mangé un citron ce matin ?", "Pfff, vous êtes un rabat-joie.",
              "Bon, je vais rigoler tout seul, alors.", "Eh ben, c'est pas la fête.", "Quelle conversation passionnante…"],
         reponses=dict(
             aime=["Moi, ce que j'aime, c'est rigoler ! Une bonne blague et je suis le plus heureux du monde.",
                   "Rire, mon vieux ! Rire, c'est la santé. Les gens trop sérieux, ça me fatigue."],
             humeur=["Excellente journée ! Comme toujours. Faut pas se laisser abattre, hein !",
                     "Super ! J'ai fait rire toute la boulangerie ce matin."],
             musique=["Tout ce qui fait danser ! Mettez-moi un bon vieux tube, et je chante avec vous.",
                      "Les chansons à boire, les trucs qu'on chante en chœur. Plus c'est bête, plus j'aime."]),
         ),
    dict(id="timide", nom="timide", bavard=0.2,
         gouts=dict(chaleureux=1, drole=0, curieux=-1, sobre=1, silence=1),
         allure=["{Il|Elle} regarde ses chaussures.", "{Il|Elle} parle tout bas.", "{Il|Elle} serre son sac contre lui."],
         bien=["Oh… merci. C'est gentil.", "Hm. Oui… c'est vrai.", "Merci… vraiment.", "Vous êtes aimable.",
               "Ça me rassure, ce que vous dites.", "Oh, c'est… c'est gentil de dire ça.", "Oui… je crois aussi.",
               "Merci de ne pas me brusquer.", "C'est agréable, de parler comme ça, doucement."],
         moyen=["Oh… d'accord.", "Hm.", "Je… je vois.", "Ah… oui.", "Peut-être…", "Euh… oui."],
         mal=["Je… je préfère ne pas en parler.", "…", "Excusez-moi, je suis fatigué{e}.", "C'est un peu personnel, ça…",
              "Je… on peut parler d'autre chose ?", "Vous posez beaucoup de questions…", "Euh… je ne sais pas quoi répondre.",
              "Je n'aime pas trop qu'on me fasse remarquer, vous savez."],
         reponses=dict(
             aime=["J'aime bien… le calme. Qu'on ne me pose pas trop de questions. Juste… être tranquille.",
                   "Les gens doux. Ceux qui ne parlent pas trop fort."],
             humeur=["Ça va… un peu fatigué{e}. Mais ça va.", "Oh… normale. Calme. C'est bien."],
             musique=["Du piano. Quelque chose de doux, sans paroles.", "Je n'écoute pas grand-chose… un peu de classique, le soir."]),
         ),
    dict(id="grincheux", nom="grincheux", bavard=0.5,
         gouts=dict(chaleureux=-1, drole=-2, curieux=0, sobre=2, silence=1),
         allure=["{Il|Elle} soupire bruyamment.", "{Il|Elle} fronce les sourcils.", "{Il|Elle} claque la portière."],
         bien=["Enfin quelqu'un de raisonnable.", "Hm. Pour une fois.", "Voilà. Ça, c'est parler.", "Vous au moins, vous ne racontez pas de bêtises.",
               "C'est bien, vous allez droit au but.", "Hmpf. Pas mal.", "Bon. Vous n'êtes pas comme les autres.",
               "Ça me change des bavards.", "Exactement ce que je pense."],
         moyen=["Hmpf.", "Si vous voulez.", "Mouais.", "Bof.", "Ça m'est égal.", "On verra."],
         mal=["Gardez vos blagues pour vous.", "Conduisez, on vous demande pas de faire le clown.", "Pfff. Épargnez-moi ça.",
              "Ah non, pas un rigolo, pas aujourd'hui.", "Vous êtes payé pour conduire, pas pour faire la causette.",
              "Ce que vous pouvez être agaçant.", "Ça, ça ne me fait pas rire du tout.", "Je n'ai pas demandé votre avis.",
              "Bon sang, quelle journée…", "Vous n'allez pas vous y mettre aussi ?"],
         reponses=dict(
             aime=["Ce que j'aime ? Qu'on me fiche la paix. Et les gens qui parlent peu, mais bien.",
                   "Le silence. Les choses simples. Pas les rigolos, en tout cas."],
             humeur=["Mauvaise. Comme d'habitude. Tout augmente, rien ne marche.", "Ne m'en parlez pas. Une catastrophe."],
             musique=["De la musique ? Du vrai, de l'ancien. Pas ce boucan qu'ils passent à la radio.",
                      "Rien. Le silence, c'est la meilleure musique."]),
         ),
    dict(id="egocentrique", nom="bavard", bavard=0.85,
         gouts=dict(chaleureux=1, drole=-1, curieux=2, sobre=-1, silence=-2),
         allure=["{Il|Elle} est déjà au téléphone en montant.", "{Il|Elle} parle avant même de s'asseoir.", "{Il|Elle} se recoiffe dans le rétroviseur."],
         bien=["Ah, vous, vous savez écouter !", "Excellente question, je vais vous raconter.", "Vous êtes quelqu'un d'intéressant, vous.",
               "Oui ! Et attendez, ce n'est pas tout.", "Ah, enfin quelqu'un qui s'intéresse !", "Je savais que vous comprendriez.",
               "Vous avez l'œil, vous.", "C'est exactement ça, et d'ailleurs…", "Vous me plaisez, on voit que vous êtes curieux."],
         moyen=["Bref.", "Oui, enfin bon.", "Ah, oui, si on veut.", "Hm. Où j'en étais ?", "Passons."],
         mal=["Vous m'écoutez, au moins ?", "Je ne vois pas ce qu'il y a de drôle.", "Bon, je vous ennuie, c'est ça ?",
              "Ah. Vous n'êtes pas très causant.", "C'est dommage, j'avais une histoire formidable.", "Vous pourriez faire un effort.",
              "On ne m'avait jamais coupé comme ça.", "Je parle tout seul, on dirait."],
         reponses=dict(
             aime=["Qu'on s'intéresse à moi, pardi ! Posez-moi des questions, j'ai mille histoires à raconter.",
                   "Les gens curieux. Ceux qui veulent savoir. Ça tombe bien, j'ai beaucoup à dire."],
             humeur=["Formidable ! J'ai eu une idée géniale ce matin, je vous raconte ?", "Très bonne, j'ai été brillant{e} en réunion."],
             musique=["Oh, j'ai fait du saxophone, vous savez. J'étais très {bon|bonne}, d'ailleurs.",
                      "Du jazz. J'ai même rencontré un grand jazzman, une fois. Une histoire incroyable."]),
         ),
    dict(id="presse", nom="pressé", bavard=0.25,
         gouts=dict(chaleureux=0, drole=-1, curieux=-1, sobre=1, silence=2),
         allure=["{Il|Elle} regarde sa montre toutes les dix secondes.", "{Il|Elle} tapote nerveusement son téléphone.", "{Il|Elle} est en retard, ça se voit."],
         bien=["Parfait. Efficace.", "Oui. Bien.", "Merci. On peut accélérer ?", "Voilà, c'est clair.", "Exactement.",
               "Bien. Continuez comme ça.", "C'est tout ce que je demande."],
         moyen=["Hm.", "Oui, oui.", "D'accord.", "Si vous voulez.", "Mm."],
         mal=["Je n'ai pas le temps pour ça.", "Concentrez-vous sur la route, s'il vous plaît.", "On ne pourrait pas éviter les bavardages ?",
              "Écoutez, je suis pressé{e}.", "Ce n'est vraiment pas le moment.", "Je dois passer un appel, là.",
              "Vous avez vu l'heure ?", "Moins de paroles, plus de kilomètres."],
         reponses=dict(
             aime=["Ce que j'aime ? Arriver à l'heure. Et qu'on ne me fasse pas perdre de temps.",
                   "L'efficacité. Les réponses courtes. Comme celle-ci."],
             humeur=["Chargée. Très chargée. Je n'ai pas le temps d'en parler.", "Trois réunions, deux retards. Voilà."],
             musique=["Je n'ai pas le temps d'écouter de la musique.", "Des podcasts, en vitesse rapide."]),
         ),
    dict(id="nostalgique", nom="nostalgique", bavard=0.7,
         gouts=dict(chaleureux=2, drole=0, curieux=1, sobre=0, silence=-1),
         allure=["{Il|Elle} regarde le paysage avec tendresse.", "{Il|Elle} serre une vieille photo.", "{Il|Elle} a les yeux un peu brillants."],
         bien=["Vous avez bon cœur, vous.", "Merci… ça me touche.", "Ah, vous me rappelez quelqu'un.", "C'est gentil de penser à ça.",
               "Oui… vous avez raison, on n'oublie pas.", "Ça fait du bien de parler d'avant.", "Vous êtes une belle personne.",
               "Ah, mon petit, vous comprenez les choses.", "Merci. Ça me réchauffe."],
         moyen=["Ah oui…", "C'est ainsi.", "Peut-être bien.", "Hm, oui.", "On verra bien."],
         mal=["Oh… vous êtes bien froid.", "Les jeunes, ça ne comprend plus rien.", "Ce n'était pas pour rire, vous savez.",
              "Ça me fait de la peine que vous disiez ça.", "On ne se moque pas des souvenirs.", "Vous ne m'écoutez pas vraiment…",
              "Avant, les gens étaient plus aimables."],
         reponses=dict(
             aime=["Ce que j'aime ? Les souvenirs, les gens chaleureux. Qu'on m'écoute raconter le temps d'avant.",
                   "La gentillesse. Un mot doux, ça vaut tout l'or du monde."],
             humeur=["Douce. J'ai repensé à ma jeunesse toute la matinée.", "Un peu mélancolique… mais c'est une jolie mélancolie."],
             musique=["Les chansons d'autrefois, l'accordéon, le bal du samedi soir…", "Ce qui passait au bal quand j'avais vingt ans."]),
         ),
    dict(id="farceur", nom="farceur", bavard=0.75,
         gouts=dict(chaleureux=0, drole=2, curieux=0, sobre=-2, silence=-1),
         allure=["{Il|Elle} a un sourire en coin.", "{Il|Elle} vous fait un clin d'œil.", "{Il|Elle} se retient de rire."],
         bien=["Ha ! Bien joué !", "Ah, je vous ai sous-estimé.", "Touché !", "Vous avez de la repartie !",
               "Ha ha, celle-là je la note.", "Un partout, la balle au centre !", "Vous êtes des nôtres !",
               "Ah, enfin un adversaire à ma taille.", "Excellent, je ris encore."],
         moyen=["Bon.", "Ouais.", "Bof, bof.", "Hm.", "Pas terrible."],
         mal=["Pfff. Quel sérieux.", "Vous êtes de la police ?", "Vous rigolez jamais, vous ?", "Allez, un petit effort d'humour !",
              "Oh là là, quel tombeau.", "Ça manque de fantaisie, tout ça.", "Vous êtes aussi drôle qu'un parcmètre.",
              "Je m'ennuie, là."],
         reponses=dict(
             aime=["Les blagues, les farces, les répliques qui fusent ! Les gens trop sérieux, je ne supporte pas.",
                   "Qu'on me renvoie la balle. Une bonne vanne, et je suis votre ami pour la vie."],
             humeur=["Excellente ! J'ai caché le dentier de mon beau-père, il le cherche encore.",
                     "Très bonne, j'ai fait croire à mon voisin que sa voiture avait été volée. Il a ri… un peu."],
             musique=["Les chansons paillardes ! Et les génériques de dessins animés.", "Tout ce qui se chante faux, très fort."]),
         ),
    dict(id="anxieux", nom="inquiet", bavard=0.55,
         gouts=dict(chaleureux=2, drole=-1, curieux=0, sobre=1, silence=-1),
         allure=["{Il|Elle} s'agrippe à la poignée.", "{Il|Elle} vérifie trois fois sa ceinture.", "{Il|Elle} a l'air tendu{e}."],
         bien=["Ah… ça me rassure, merci.", "Oui, vous avez raison, ça va aller.", "Merci, vous êtes calme, ça aide.",
               "Pfiou. Merci de dire ça.", "D'accord… je respire.", "Vous êtes rassurant, vous savez.",
               "Merci, j'avais besoin d'entendre ça."],
         moyen=["Ah… oui.", "Si vous le dites.", "J'espère.", "Hm… d'accord.", "Peut-être."],
         mal=["Ce n'est pas drôle, je suis {inquiet|inquiète} !", "Vous me stressez, là.", "Oh non, ne dites pas ça…",
              "Vous plaisantez, mais moi je m'inquiète vraiment.", "Ça ne m'aide pas du tout.", "Arrêtez, vous me faites peur.",
              "Je n'aurais pas dû prendre ce taxi."],
         reponses=dict(
             aime=["J'aime qu'on me rassure. Les gens calmes, gentils. Les blagues, ça me met mal à l'aise quand je suis tendu{e}.",
                   "Qu'on me parle doucement. Un mot gentil et je me détends."],
             humeur=["Stressante. Je m'inquiète pour un rien, vous savez.", "Pas terrible, j'ai un rendez-vous important."],
             musique=["De la musique douce, pour me calmer.", "Les bruits de la nature. La pluie, la mer."]),
         ),
]

# ---------------------------------------------------------------- identité (comme avant)
PRENOMS = dict(
    f=["Josiane", "Martine", "Chantal", "Nathalie", "Sandrine", "Léa", "Camille", "Inès", "Monique", "Brigitte", "Sophie",
       "Manon", "Odette", "Yvette", "Clara", "Fatima", "Aurélie", "Ginette"],
    m=["Gérard", "Michel", "Patrick", "Thierry", "Kévin", "Lucas", "Hugo", "Mohamed", "Bernard", "Jean-Pierre", "Christophe",
       "Théo", "Marcel", "Raymond", "Julien", "Didier", "Yannick", "Roger"])
METIERS = [
    dict(m="boulanger", f="boulangère", detail="Debout à trois heures tous les matins."),
    dict(m="infirmier", f="infirmière", detail="Je fais les tournées à domicile dans les villages."),
    dict(m="agriculteur", f="agricultrice", detail="Des vaches laitières, du maïs, et pas de vacances."),
    dict(m="professeur", f="professeure", detail="J'enseigne l'histoire au collège."),
    dict(m="retraité", f="retraitée", detail="Après quarante ans à l'usine."),
    dict(m="étudiant", f="étudiante", detail="En deuxième année, à Lyon."),
    dict(m="maçon", f="maçonne", detail="J'ai monté la moitié des murets du coin."),
    dict(m="facteur", f="factrice", detail="Je connais toutes les boîtes aux lettres de la vallée."),
    dict(m="coiffeur", f="coiffeuse", detail="J'ai mon salon près de la place."),
    dict(m="garagiste", f="garagiste", detail="Je répare surtout des tracteurs et des vieilles voitures."),
    dict(m="comptable", f="comptable", detail="Des chiffres toute la journée."),
    dict(m="musicien", f="musicienne", detail="Je joue dans les mariages et les fêtes de village."),
    dict(m="pharmacien", f="pharmacienne", detail="On me raconte tous les bobos du canton."),
    dict(m="cuisinier", f="cuisinière", detail="Au restaurant, en bas de la côte."),
    dict(m="routier", f="routière", detail="Toute la semaine sur l'autoroute."),
    dict(m="apiculteur", f="apicultrice", detail="Quarante ruches sur les collines."),
]
LOISIRS = ["la pétanque", "la randonnée sur les collines", "le jardinage", "la pêche à l'étang", "le vélo", "les mots croisés",
           "la chorale", "le rugby", "la belote", "la danse de salon", "les champignons", "la photo"]
ANIMAUX = ["un chat qui s'appelle Moustache", "un vieux chien, Pistache", "trois poules", "un perroquet qui parle trop",
           "deux lapins", "un poisson rouge, Bulle", "un âne, Cadichon"]
FAMILLES = ["deux petits-enfants", "un fils à Lyon", "une fille qui vit au Canada", "des jumeaux de six ans",
            "une grande famille, on est onze à Noël", "personne, et c'est très bien comme ça", "un frère qui ne m'appelle jamais"]

# ---------------------------------------------------------------- questions du joueur (bouton « parler »)
# chaque question : variantes dites par le joueur ; réponse : « fait » commun (identité) ou réponse du caractère
QUESTIONS = [
    dict(id="metier", t=["Vous faites quoi dans la vie ?", "Vous travaillez dans quoi ?", "C'est quoi, votre métier ?"],
         fait=["Je suis {metier}. {metier_detail}", "{metier}. {metier_detail} Ça vous étonne ?"]),
    dict(id="famille", t=["Vous avez de la famille par ici ?", "Vous avez des enfants ?", "Quelqu'un vous attend, ce soir ?"],
         fait=["J'ai {famille}.", "Oh, j'ai {famille}. C'est comme ça."]),
    dict(id="loisir", t=["Vous faites quoi, le week-end ?", "Vous avez une passion ?", "Qu'est-ce qui vous occupe, à part le travail ?"],
         fait=["Moi, c'est {loisir}. Tous les dimanches.", "{loisir}, sans hésiter. J'en ferais tous les jours."]),
    dict(id="animal", t=["Vous avez des animaux ?", "Il y a des bêtes, chez vous ?"],
         fait=["J'ai {animal}.", "Oui, j'ai {animal}. Une vraie personne de la famille."]),
    dict(id="origine", t=["Vous êtes d'ici ?", "Vous habitez dans le coin ?", "Vous venez d'où, comme ça ?"],
         fait=["J'habite à {commune}, depuis toujours.", "De {commune}. C'est petit, mais on s'y plaît."]),
    dict(id="destination", t=["Vous allez faire quoi, là-bas ?", "C'est pour quoi, cette course ?"],
         fait=["Je vais à {dest}. Une affaire à régler.", "{dest}, à {dest_commune}. On m'attend."]),
    dict(id="aime", t=["Qu'est-ce qui vous fait plaisir, en général ?", "Vous êtes plutôt du genre à rire ou à rester tranquille ?",
                       "Qu'est-ce que vous aimez, dans la vie ?"]),
    dict(id="humeur", t=["Vous avez passé une bonne journée ?", "Comment ça va, aujourd'hui ?", "Ça va, vous ? Pas trop fatigué ?"]),
    dict(id="musique", t=["Vous écoutez quoi, comme musique ?", "Je mets un peu de musique ? Vous aimez quoi ?"]),
]
# le client n'a pas envie de répondre (taiseux, pressé…)
ESQUIVE = ["Je préfère ne pas répondre.", "Ça ne vous regarde pas trop, si ?", "On parlera de ça une autre fois.",
           "Hm. Regardez la route, plutôt."]

# ---------------------------------------------------------------- fils de conversation (le client parle)
# trois échanges : « dit » du client, puis une réponse par ton (le jeu en montre trois)
def N(dit, chaleureux, drole, curieux, sobre):
    return dict(dit=dit, rep=dict(chaleureux=chaleureux, drole=drole, curieux=curieux, sobre=sobre))

FILS = {
    "metier": [
        [N("Je suis {metier}. {metier_detail}", "Ça doit être passionnant !", "Moi je conduis, c'est déjà du sport.",
           "Et ça vous plaît toujours ?", "Je vois."),
         N("Il y a des jours avec, et des jours sans. Ce matin, c'était un jour sans.", "Courage, ça va s'arranger.",
           "Un jour sans quoi ? Sans café ?", "Qu'est-ce qui s'est passé ?", "Ça arrive."),
         N("Enfin, je ne changerais pour rien au monde, je crois.", "C'est beau d'aimer ce qu'on fait.",
           "Même pas pour être chauffeur de taxi ?", "Vous avez déjà pensé à faire autre chose ?", "Tant mieux.")],
        [N("Vous savez, mon métier, on ne s'en rend pas compte, mais c'est fatigant.", "J'imagine, vous méritez du repos.",
           "Plus fatigant que d'écouter mes clients ?", "Qu'est-ce qui est le plus dur ?", "Comme tous les métiers."),
         N("Les horaires, surtout. Je ne vois plus mes amis.", "Il faut prendre du temps pour vous.",
           "Vos amis vous attendent sûrement au café.", "Vous travaillez combien d'heures, en vrai ?", "Les horaires, oui."),
         N("Bah. On fait avec. Et puis il faut bien payer les factures.", "Vous avez du courage, en tout cas.",
           "Les factures, elles, ne prennent jamais de vacances.", "Vous pourriez changer de rythme ?", "C'est la vie.")],
        [N("J'ai commencé tout jeune, vous savez. À seize ans.", "Quel parcours, chapeau.", "À seize ans, moi je dormais jusqu'à midi.",
           "Qui vous a appris le métier ?", "Tôt, en effet."),
         N("C'est mon oncle qui m'a tout appris. Un caractère, celui-là.", "Il doit être fier de vous.",
           "Un caractère de cochon ou un caractère en or ?", "Il fait toujours le métier ?", "Je vois le genre."),
         N("Il est parti l'an dernier. Je pense souvent à lui en travaillant.", "Il continue de vous accompagner, alors.",
           "Je suis sûr qu'il vous surveille d'en haut.", "Quel souvenir vous reste de lui ?", "Je suis désolé.")],
    ],
    "maison": [
        [N("J'habite à {commune}, depuis toujours.", "C'est un joli coin.", "Toujours ? Même avant votre naissance ?",
           "Ça a beaucoup changé, depuis ?", "D'accord."),
         N("Avant, il y avait trois cafés et une épicerie. Maintenant, plus rien.", "C'est triste, ces villages qui se vident.",
           "Il reste au moins le taxi !", "Qu'est-ce qui vous manque le plus ?", "C'est partout pareil."),
         N("Mais les voisins sont toujours là. Ça, c'est précieux.", "Les bons voisins, c'est un trésor.",
           "Tant qu'ils ne font pas de karaoké le soir.", "Vous vous voyez souvent ?", "C'est important.")],
        [N("J'ai fait refaire ma toiture cet été. Quelle histoire !", "Au moins, vous serez au sec cet hiver.",
           "Vous avez retrouvé un nid d'hirondelles dans la facture ?", "Qu'est-ce qui s'est passé ?", "Les travaux, toujours long."),
         N("L'artisan est venu trois fois en quatre mois. Trois fois !", "Quelle patience vous avez eue.",
           "Il devait faire le tour de la France en tuiles.", "Vous avez fini par en trouver un autre ?", "C'est fréquent."),
         N("Enfin, c'est fini. Et c'est beau, je dois dire.", "Vous pouvez en être fier.", "Il faudra pendre la crémaillère !",
           "Vous avez choisi quelle couleur de tuiles ?", "Tant mieux.")],
        [N("Mon jardin, c'est toute ma fierté. Des tomates, des courges, des haricots…", "Ça doit être un bonheur.",
           "Vous me gardez une courge pour Halloween ?", "Quel est votre secret pour les tomates ?", "Bel endroit, sûrement."),
         N("Le secret, c'est de leur parler. Si, si, je vous assure.", "C'est joli, cette idée.", "Et elles vous répondent ?",
           "Vous leur dites quoi, aux tomates ?", "Pourquoi pas."),
         N("Cette année, elles étaient énormes. Le voisin est jaloux.", "Bravo, c'est mérité.",
           "Faites attention, il va venir les voler la nuit.", "Vous en faites quoi, de tout ça ?", "Belle récolte.")],
    ],
    "famille": [
        [N("J'ai {famille}.", "C'est une richesse, la famille.", "Et ça fait du bruit, à Noël ?", "Vous les voyez souvent ?", "D'accord."),
         N("Pas aussi souvent que je voudrais. Tout le monde court partout.", "Chaque moment ensemble compte, alors.",
           "Il faudrait leur offrir un taxi.", "Qu'est-ce qui vous empêche de les voir ?", "C'est la vie moderne."),
         N("Dimanche, on fait un grand repas. J'ai hâte.", "Ça va être un beau moment.", "Prévoyez le pantalon élastique.",
           "Qu'est-ce que vous allez cuisiner ?", "Bon dimanche, alors.")],
        [N("Ma fille vient de m'annoncer qu'elle attend un bébé !", "Oh, quelle merveilleuse nouvelle !",
           "Vous allez devenir une star des photos de famille.", "C'est pour quand ?", "Félicitations."),
         N("Au printemps. Je suis tellement ému{e}, je n'en dors plus.", "C'est normal, c'est un bonheur immense.",
           "Profitez du sommeil tant qu'il en reste !", "Vous savez si c'est une fille ou un garçon ?", "Je comprends."),
         N("Je tricote déjà des petits chaussons. Je suis {nul|nulle} en tricot.", "Ce sera le plus beau cadeau.",
           "Des chaussons asymétriques, c'est tendance.", "Vous en avez fait combien ?", "L'intention compte.")],
        [N("Mon frère et moi, on ne se parle plus depuis dix ans.", "C'est dur, ces silences en famille.",
           "Dix ans ? Il doit avoir des choses à raconter.", "Qu'est-ce qui s'est passé ?", "Ça arrive."),
         N("Une histoire d'héritage. Une maison. Des bêtises, au fond.", "C'est souvent pour des choses comme ça.",
           "Une maison, ça ne vaut pas un frère. Sauf avec piscine.", "Vous aimeriez renouer ?", "Je vois."),
         N("Peut-être que je l'appellerai. Un jour. Peut-être.", "Je suis sûr qu'il attend ce coup de fil.",
           "Appelez-le, et proposez-lui un taxi.", "Qu'est-ce qui vous retient ?", "C'est à vous de voir.")],
    ],
    "loisir": [
        [N("Moi, ma passion, c'est {loisir}.", "C'est bien d'avoir une passion.", "Vous êtes champion départemental, j'espère ?",
           "Depuis quand vous en faites ?", "Pas mal."),
         N("Depuis vingt ans. Et je ne m'en lasse pas.", "C'est beau, cette fidélité.", "Vingt ans, ça mérite une médaille.",
           "Qu'est-ce qui vous plaît tant ?", "Bel engagement."),
         N("C'est le seul moment où j'oublie tout. Le reste disparaît.", "On en a tous besoin, de ces moments-là.",
           "Même les impôts ?", "Vous en faites avec des amis ?", "Je comprends.")],
        [N("Ce week-end, il y a un concours de belote à la salle des fêtes.", "Ça va être une belle soirée.",
           "Attention, les mamies trichent, je le sais.", "Vous jouez souvent ?", "Bonne chance."),
         N("L'an dernier, j'ai fini deuxième. À cause d'une dame de pique.", "Deuxième, c'est déjà très bien.",
           "La dame de pique, toujours elle.", "Qui a gagné, alors ?", "Pas de chance."),
         N("Cette année, je vise la première place. J'ai de l'entraînement.", "Je vous la souhaite de tout cœur.",
           "Je parie sur vous, double ou rien.", "Vous vous entraînez comment ?", "On verra.")],
        [N("J'ai trouvé des cèpes énormes la semaine dernière dans les bois.", "Quelle chance, ça doit être délicieux.",
           "Vous me dites où ? Non, je plaisante. Quoique…", "Vous les avez cuisinés comment ?", "Joli."),
         N("Mais je ne dirai jamais où. Même sous la torture.", "C'est votre petit secret, c'est normal.",
           "Je vous suivrai en taxi, discrètement.", "Ça fait longtemps que vous connaissez le coin ?", "Je respecte."),
         N("Mon père m'emmenait déjà là-bas quand j'étais petit{e}.", "C'est un joli souvenir à garder.",
           "Les champignons de famille, ça se transmet.", "Vous y emmenez vos enfants, à votre tour ?", "Belle tradition.")],
    ],
    "nouvelles": [
        [N("Vous avez entendu ? Ils vont refaire la route de la vallée.", "Enfin, elle en a bien besoin.",
           "Ils vont boucher les nids-de-poule ? Les poules vont être déçues.", "Vous savez quand commencent les travaux ?",
           "Je ne savais pas."),
         N("Six mois de travaux, paraît-il. Avec des déviations partout.", "Il faudra être patient.",
           "Six mois, en langage de travaux, ça fait deux ans.", "Vous passez souvent par là ?", "Ça va être long."),
         N("Bon, au moins, après, ce sera tout lisse.", "On en profitera tous.", "Idéal pour les courses de taxis.",
           "Vous pensez que ça va changer quelque chose ?", "On verra bien.")],
        [N("La boulangerie de la place a changé de propriétaire.", "J'espère qu'ils sont gentils.",
           "Tant que les croissants restent, je pardonne tout.", "Qui l'a reprise ?", "Ah bon."),
         N("Un jeune couple de Lyon. Ils font du pain au levain, avec des graines.", "C'est bien, des jeunes qui s'installent.",
           "Du pain avec des graines, mes oiseaux vont adorer.", "Vous l'avez goûté ?", "Je vois."),
         N("Les anciens râlent, mais tout le monde y va quand même.", "C'est plutôt bon signe, alors.",
           "Râler, c'est le sport national.", "Vous en pensez quoi, vous ?", "Classique.")],
        [N("Il paraît qu'on a vu un loup sur les collines, la semaine dernière.", "Pourvu que les bêtes soient en sécurité.",
           "Un loup ? Ou le chien du voisin mal coiffé ?", "Qui l'a vu ?", "Étonnant."),
         N("Un chasseur, au petit matin. Il est formel.", "Il a dû avoir peur, le pauvre.",
           "Les chasseurs sont toujours formels.", "Il a pris une photo ?", "Je vois."),
         N("En tout cas, je ne vais plus aux champignons seul{e}.", "C'est plus prudent, oui.",
           "Prenez un sifflet et une côtelette.", "Vous y croyez vraiment ?", "Sage décision.")],
    ],
    "meteo": [
        [N("Quel temps, aujourd'hui !", "C'est vrai que c'est agréable.", "Un temps à faire sécher le linge et les chauffeurs.",
           "Vous aimez cette saison ?", "Oui."),
         N("Moi, je préfère l'automne. Les couleurs sur les collines…", "C'est magnifique, l'automne ici.",
           "Et les feuilles mortes dans les gouttières.", "Qu'est-ce qui vous plaît, en automne ?", "C'est joli."),
         N("Et puis l'odeur des feux de bois, le soir. Ça me rappelle mon enfance.", "C'est une odeur réconfortante.",
           "Et celle des châtaignes grillées, surtout.", "Vous avez grandi à la campagne ?", "Je comprends.")],
        [N("Ils annoncent de l'orage pour ce soir.", "Rentrez bien au chaud, alors.", "Je vais laver la voiture, il pleuvra sûrement.",
           "Vous avez peur de l'orage ?", "On verra."),
         N("La dernière fois, la grêle a abîmé toutes mes salades.", "Quel dommage, après tant de travail.",
           "Des salades en confettis, c'est original.", "Vous avez pu les sauver ?", "Pas de chance."),
         N("Cette fois, j'ai mis des bâches. On verra bien.", "Vous avez bien fait.", "Les bâches, l'arme secrète du jardinier.",
           "Vous avez d'autres astuces ?", "Prudent.")],
        [N("Il fait une de ces chaleurs, l'été maintenant.", "Ce n'est pas facile pour tout le monde.",
           "Même la clim de mon taxi transpire.", "Vous trouvez que ça a changé ?", "C'est vrai."),
         N("Quand j'étais jeune, il neigeait tous les hivers, ici.", "C'était un autre temps.", "Et vous alliez à l'école en luge ?",
           "Vous vous souvenez du dernier grand hiver ?", "Les choses changent."),
         N("Mes petits-enfants n'ont jamais fait de bonhomme de neige.", "C'est triste, j'espère qu'ils en feront un.",
           "Il reste la mousse à raser.", "Vous les emmenez à la montagne ?", "C'est dommage.")],
    ],
    "meteo_pluie": [
        [N("Quel temps de chien, avec cette pluie !", "Heureusement, vous êtes au sec ici.", "Les chiens, eux, ont un parapluie ?",
           "Ça fait longtemps qu'il pleut comme ça ?", "Oui, il pleut."),
         N("Mon jardin va être noyé. Mes tomates n'aiment pas ça du tout.", "Elles vont s'en remettre, j'en suis sûr.",
           "Faites-leur des petits imperméables.", "Vous les avez protégées ?", "C'est la météo."),
         N("Enfin, la nature en avait besoin, il paraît.", "C'est vrai, tout va reverdir.",
           "Et les escargots sont ravis.", "Vous avez un puits pour récupérer l'eau ?", "Sans doute.")],
        [N("Faites attention, ça glisse sur ces petites routes.", "Ne vous en faites pas, je suis prudent.",
           "Pas de souci, j'ai des pneus de pédalo.", "Vous avez déjà eu un accident ?", "Je fais attention."),
         N("Mon cousin est parti dans le fossé l'an dernier, par un temps pareil.", "J'espère qu'il n'a rien eu.",
           "Il a dû trouver le fossé très confortable.", "Comment ça s'est passé ?", "Ça arrive vite."),
         N("Plus de peur que de mal. Mais depuis, je suis {inquiet|inquiète} sous la pluie.", "C'est bien normal, je roule doucement.",
           "Je promets de ne pas tester le fossé.", "Vous préférez qu'on ralentisse ?", "Compris.")],
    ],
    "musique": [
        [N("Elle est bien, cette chanson. Vous pouvez monter un peu ?", "Avec plaisir, profitez-en.",
           "Je monte, mais je ne chante pas, promis.", "Vous la connaissez ?", "Bien sûr."),
         N("Ça me rappelle le bal de quatorze juillet, il y a des années.", "Quel joli souvenir.",
           "Vous dansiez le twist sur les tables ?", "Vous dansiez bien ?", "Je vois."),
         N("J'y ai rencontré quelqu'un, ce soir-là. Mais c'est une autre histoire.", "Les plus belles histoires commencent au bal.",
           "Vous ne pouvez pas me laisser comme ça !", "Racontez-moi, on a le temps.", "D'accord.")],
        [N("La musique d'aujourd'hui, je n'y comprends plus rien.", "Chaque génération a la sienne.",
           "Moi non plus, je fais semblant pour mes enfants.", "Qu'est-ce que vous écoutiez, vous ?", "Les goûts changent."),
         N("Avant, il y avait des mélodies. Des paroles qu'on pouvait chanter.", "Ces chansons-là restent dans le cœur.",
           "Maintenant, il y a des paroles qu'on ne peut pas répéter.", "Vous avez un chanteur préféré ?", "C'est vrai."),
         N("Je chante encore à la chorale, le jeudi soir.", "C'est beau de continuer à chanter.",
           "Je viendrai faire le chœur des chauffeurs.", "Vous chantez quoi, en ce moment ?", "Très bien.")],
    ],
    "souvenir": [
        [N("Vous savez, je passais par ici quand j'étais petit{e}, à vélo.", "C'est émouvant de revoir ces endroits.",
           "Vous aviez déjà un vélo avec turbo ?", "Ça a beaucoup changé ?", "Ah oui."),
         N("Il y avait un vieux pommier, là-bas. On volait les pommes.", "Les meilleures pommes sont les pommes volées.",
           "Le propriétaire vous attend encore avec son fusil.", "Le pommier est toujours là ?", "Je vois."),
         N("Il a été coupé. Mais je le vois encore, quand je passe.", "Il vit dans vos souvenirs, alors.",
           "Un pommier fantôme, ça fait des compotes invisibles.", "Qu'est-ce qu'il y a à la place ?", "C'est comme ça.")],
        [N("Mon premier travail, c'était dans une usine de tissage, à côté.", "Ça a dû être une sacrée époque.",
           "Vous avez tissé ce siège, peut-être ?", "Comment c'était, l'usine ?", "D'accord."),
         N("Le bruit des machines, toute la journée. On ne s'entendait pas parler.", "Ça devait être épuisant.",
           "Pratique pour ne pas écouter son chef.", "Vous gardez de bons souvenirs quand même ?", "Dur métier."),
         N("Mais on était une vraie bande. On riait beaucoup, à la pause.", "Ce sont ces moments-là qui restent.",
           "Les pauses, le vrai cœur du métier.", "Vous vous voyez encore ?", "C'est bien.")],
    ],
    "cuisine": [
        [N("Ce soir, je fais un gratin dauphinois. Le vrai, sans fromage.", "Ça a l'air délicieux.",
           "Sans fromage ? Vous êtes un rebelle.", "C'est quoi, votre secret ?", "Bon appétit."),
         N("Le secret, c'est l'ail et la crème. Beaucoup de crème.", "C'est la cuisine qui réchauffe.",
           "Et un cardiologue pas trop loin.", "Vous tenez la recette de qui ?", "Classique."),
         N("C'était la recette de ma grand-mère. Personne ne le réussit comme elle.", "Je suis sûr que vous le faites très bien.",
           "Elle doit vous surveiller depuis le four.", "Vous la cuisinez souvent ?", "Les grands-mères, oui.")],
        [N("Vous connaissez le restaurant près de la mairie ?", "On m'en a dit du bien.", "Celui où on ressort en roulant ?",
           "Vous y allez souvent ?", "De nom."),
         N("Leurs quenelles sont les meilleures du département.", "Il faudra que j'essaie.",
           "Je les pensais réservées aux Lyonnais.", "Avec quelle sauce ?", "D'accord."),
         N("Sauce Nantua, bien sûr. Il n'y a pas débat.", "Je vous fais confiance.", "Le débat est clos, maître.",
           "C'est fait avec des écrevisses, c'est ça ?", "Entendu.")],
    ],
    "animaux": [
        [N("J'ai {animal}. Il me rend chèvre.", "C'est un vrai membre de la famille.",
           "C'est lui qui commande, à la maison ?", "Qu'est-ce qu'il a fait encore ?", "Les animaux, oui."),
         N("Hier, il a mangé une chaussette entière. Une chaussette !", "Pauvre bête, j'espère qu'il va bien.",
           "Il avait faim de mode.", "Il va bien, après ça ?", "Ça arrive."),
         N("Le vétérinaire a dit que ce n'était pas la première fois qu'il voyait ça.", "Ça me rassure pour lui.",
           "Il a une collection de chaussettes, ce vétérinaire.", "Vous allez cacher vos chaussettes, maintenant ?", "Tant mieux.")],
        [N("Les vaches du voisin se sont encore échappées ce matin.", "J'espère que personne n'a été blessé.",
           "Elles voulaient prendre le taxi, sûrement.", "Où est-ce qu'elles sont allées ?", "Ça arrive à la campagne."),
         N("Sur la route départementale ! Il a fallu une heure pour les ramener.", "Quelle frayeur pour tout le monde.",
           "Un embouteillage de vaches, c'est très rural.", "Comment vous les avez rattrapées ?", "Long."),
         N("Avec un seau de grain. Les vaches, c'est comme les gens : par le ventre.", "Bien trouvé, la douceur marche toujours.",
           "Je retiens l'astuce pour mes clients.", "Vous avez grandi dans une ferme ?", "Malin.")],
    ],
    "sport": [
        [N("Vous avez vu le match de rugby, dimanche ?", "Il paraît que c'était un beau match.",
           "J'ai vu le troisième mi-temps, ça compte ?", "Qui a gagné ?", "Pas vu."),
         N("Bourgoin a gagné de deux points ! À la dernière seconde !", "Quelle émotion, ça a dû être !",
           "Le cœur des supporters a dû lâcher.", "Qui a marqué ?", "Bravo à eux."),
         N("Toute la tribune s'est levée. J'en ai encore des frissons.", "Ce sont des moments magiques.",
           "Et votre voisin de tribune a perdu sa casquette.", "Vous y allez tous les dimanches ?", "Beau souvenir.")],
        [N("Je me suis mis{e} à la course à pied, à mon âge.", "C'est formidable, bravo !", "Vous courez après le bus ?",
           "Vous courez où ?", "Bonne idée."),
         N("Le long de la Bourbre, le matin. Trois kilomètres, pour l'instant.", "C'est déjà très bien, continuez.",
           "Trois kilomètres, et le café à l'arrivée.", "Vous avez un objectif ?", "C'est un début."),
         N("Je voudrais faire la course du village, au printemps.", "Vous y arriverez, j'en suis sûr.",
           "Je viendrai vous encourager avec un klaxon.", "C'est quelle distance ?", "Bonne chance.")],
    ],
    "vacances": [
        [N("Je pars en vacances la semaine prochaine. Enfin !", "Vous l'avez bien mérité.", "Emmenez-moi dans la valise.",
           "Vous allez où ?", "Bonnes vacances."),
         N("En Bretagne. Il paraît qu'il pleut, mais j'aime ça.", "La Bretagne, c'est magnifique.",
           "Il pleut seulement sur les gens qui ne sont pas bretons.", "Vous y êtes déjà allé{e} ?", "Bon choix."),
         N("Des crêpes, la mer, et pas de téléphone. Le rêve.", "Profitez de chaque instant.",
           "Et le cidre, surtout le cidre.", "Vous allez réussir à couper le téléphone ?", "Profitez.")],
        [N("Cette année, on ne part pas. Trop cher.", "Il y a de belles choses à faire par ici aussi.",
           "Les vacances au balcon, c'est très tendance.", "Qu'est-ce que vous allez faire, alors ?", "C'est comme ça."),
         N("Des balades sur les collines, des pique-niques au lac.", "Ça a l'air très doux, comme programme.",
           "Et des selfies devant le château, comme les touristes.", "Vous connaissez un bon coin ?", "Bien."),
         N("Finalement, on est bien, chez nous. On l'oublie parfois.", "C'est vrai, c'est une belle région.",
           "Et pas d'embouteillages sur l'autoroute.", "Qu'est-ce que vous préférez, ici ?", "C'est vrai.")],
    ],
    "route": [
        [N("Vous conduisez bien, pour un taxi.", "Merci, c'est gentil.", "Pour un taxi ? Je vais le prendre mal.",
           "Les autres conduisent mal ?", "Merci."),
         N("Le dernier m'a fait faire trois fois le tour du rond-point.", "Ça a dû être désagréable.",
           "Il visitait le rond-point en détail.", "Il s'était perdu ?", "Ça arrive."),
         N("Il cherchait la sortie. Il a fini par me demander le chemin.", "Je vous promets que je connais la route.",
           "Il vous a au moins fait une réduction ?", "Et vous lui avez indiqué ?", "Je connais le chemin.")],
        [N("C'est joli, cette route, avec les collines.", "C'est vrai, je ne m'en lasse pas.", "Et sans péage, en plus.",
           "Vous connaissez l'histoire du coin ?", "Oui."),
         N("Là-haut, il y avait un château fort, au Moyen Âge.", "Ça devait être impressionnant.",
           "Avec un taxi à cheval pour monter ?", "Il en reste quelque chose ?", "Je ne savais pas."),
         N("Il reste quelques pierres. Les gamins y jouent aux chevaliers.", "C'est beau, que ça vive encore.",
           "Et les parents jouent aux dragons.", "Vous y alliez, enfant ?", "Joli.")],
    ],
    "destination": [
        [N("Vous connaissez {dest} ?", "Oui, c'est un endroit agréable.", "Je connais tout, je suis un GPS humain.",
           "Vous y allez pour quoi ?", "Oui."),
         N("J'y vais pour la première fois. Je suis un peu stressé{e}.", "Ça va bien se passer, vous verrez.",
           "Pas de stress, au pire on fait demi-tour.", "Qu'est-ce qui vous inquiète ?", "Ça ira."),
         N("Merci de m'y conduire, en tout cas.", "Avec plaisir, c'est mon métier.", "Je vous dépose même devant la porte.",
           "Vous rentrez comment, après ?", "Je vous en prie.")],
        [N("À {dest_commune}, il y a un marché formidable le samedi.", "J'adore les marchés de village.",
           "Avec des poules qui font la queue ?", "Qu'est-ce qu'on y trouve ?", "Ah bon."),
         N("Du fromage, du miel, des légumes. Et des ragots, surtout.", "C'est ça, la vie de village.",
           "Les ragots sont-ils bio ?", "Vous y allez chaque semaine ?", "Je vois."),
         N("Si vous passez, goûtez le saint-marcellin du stand bleu.", "Je n'y manquerai pas, merci.",
           "Je le mettrai en note de frais.", "Il est comment, ce fromage ?", "Noté.")],
    ],
}


# ---------------------------------------------------------------- deuxième série de fils
PLUS = {
    "metier": [
        [N("Aujourd'hui, j'ai eu une journée de fou au travail.", "Vous allez pouvoir vous reposer, maintenant.",
           "De fou, ou de fou furieux ?", "Qu'est-ce qui s'est passé ?", "Ça arrive."),
         N("Mon chef m'a demandé de tout refaire. Trois semaines de travail.", "C'est injuste, je comprends que ça vous pèse.",
           "Il voulait peut-être juste vous occuper.", "Il vous a expliqué pourquoi ?", "C'est rageant."),
         N("Bon. Demain est un autre jour, comme on dit.", "Exactement, et vous avez bien mérité votre soirée.",
           "Et demain, c'est peut-être lui qui refait tout.", "Vous allez faire quoi, ce soir, pour vous détendre ?", "C'est sage.")],
        [N("On m'a proposé une promotion. Mais il faudrait déménager à Paris.", "C'est une belle reconnaissance, bravo.",
           "Paris ? Il y a des collines, au moins ?", "Vous en avez envie ?", "Grosse décision."),
         N("Je ne sais pas. Ici, j'ai mes habitudes, mes amis, mon jardin.", "Ce sont des choses précieuses, aussi.",
           "Et votre taxi préféré, surtout.", "Qu'est-ce qui vous retient le plus ?", "Je comprends."),
         N("Je crois que je vais dire non. La vie est trop courte.", "Ça me semble une sage décision.",
           "Paris perd quelqu'un de bien, tant pis pour eux.", "Vous ne regretterez pas ?", "C'est votre choix.")],
        [N("Je viens de prendre ma retraite. C'est mon premier jour.", "Félicitations, profitez bien de ce nouveau temps !",
           "Premier jour de vacances pour toujours !", "Qu'est-ce que vous allez faire, maintenant ?", "Félicitations."),
         N("C'est bizarre. Je me suis réveillé{e} à six heures, par habitude.", "Ça viendra, il faut le temps de s'habituer.",
           "Le réveil a pris sa retraite plus tard que vous.", "Qu'est-ce qui va vous manquer ?", "C'est normal."),
         N("Les collègues, surtout. On a ri pendant trente ans.", "Vous pourrez continuer à les voir, j'en suis sûr.",
           "Organisez des pots de retraite toutes les semaines.", "Vous avez prévu de les revoir ?", "Ça se comprend.")],
    ],
    "nouvelles": [
        [N("Le maire a annoncé une fête de village pour la fin du mois.", "Ça va être une belle occasion de se retrouver.",
           "Avec un bal et des saucisses, j'espère.", "Qu'est-ce qui est prévu ?", "Ah, bien."),
         N("Un repas sur la place, un concours de pétanque et un feu d'artifice.", "C'est un joli programme.",
           "Le feu d'artifice, c'est pour la pétanque ?", "Vous allez y participer ?", "Complet."),
         N("Je tiens la buvette, comme chaque année. Venez donc !", "Avec plaisir, si je ne travaille pas.",
           "Je viendrai en taxi, pour pouvoir trinquer.", "Vous servez quoi, à la buvette ?", "Peut-être.")],
        [N("Vous savez que l'école du village risque de fermer ?", "Ce serait vraiment dommage.",
           "Les enfants vont applaudir, les parents moins.", "Pourquoi elle fermerait ?", "Ah bon."),
         N("Plus assez d'enfants. Quatorze élèves, toutes classes confondues.", "C'est le cœur du village, pourtant.",
           "Quatorze, c'est une équipe de rugby et demie.", "Il y a une solution ?", "C'est peu."),
         N("Les parents font une pétition. J'ai signé, bien sûr.", "Vous avez bien fait, il faut se battre.",
           "Je signe aussi, même avec mon permis de conduire.", "Ça peut marcher, à votre avis ?", "Bien.")],
        [N("Il y a eu un cambriolage chez les voisins, cette semaine.", "Ça doit être terrible pour eux.",
           "Ils ont emporté le nain de jardin ?", "Qu'est-ce qui a été volé ?", "C'est malheureux."),
         N("La télé, l'ordinateur, et les bijoux de la grand-mère.", "Les souvenirs, c'est le plus dur à perdre.",
           "Et ils ont laissé la belle-mère, pas de chance.", "La police a des pistes ?", "Je vois."),
         N("Depuis, tout le monde ferme ses volets. Ça change l'ambiance.", "C'est triste de vivre dans la méfiance.",
           "Les volets n'ont jamais autant servi.", "Vous avez installé une alarme, vous ?", "Prudence.")],
    ],
    "famille": [
        [N("Mon petit-fils passe son permis de conduire demain.", "Je lui souhaite plein de réussite !",
           "Prévenez les autres conducteurs.", "C'est sa première fois ?", "Bonne chance à lui."),
         N("C'est sa troisième tentative. Il cale toujours au démarrage.", "La troisième sera la bonne, j'en suis sûr.",
           "Au moins, il ne roule pas trop vite.", "Il est stressé ?", "Ça arrive."),
         N("S'il l'a, il pourra m'emmener faire les courses. Fini le taxi !", "Ce sera une belle fierté pour vous deux.",
           "Vous allez me faire perdre une cliente !", "Il conduit comment, en vrai ?", "Bien sûr.")],
        [N("Ma mère a quatre-vingt-quinze ans et elle conduit encore.", "Quelle énergie, c'est formidable !",
           "Il faut que je fasse attention à elle sur la route.", "Elle a quel secret ?", "Étonnant."),
         N("Elle dit que c'est grâce à un petit verre de vin chaque soir.", "C'est une jolie philosophie de vie.",
           "Je note : un petit verre, mais pas avant de conduire.", "Elle a toujours vécu ici ?", "Pourquoi pas."),
         N("Elle me répète que je suis trop sérieux{e}. À mon âge !", "Les mamans restent des mamans.",
           "Elle a peut-être raison, vous savez.", "Et vous, vous vous trouvez trop sérieux ?", "C'est drôle.")],
    ],
    "souvenir": [
        [N("Ici, avant, il y avait un cinéma. Le samedi soir, c'était plein.", "Ça devait être un lieu magique.",
           "Avec des films muets et un pianiste ?", "Vous y alliez souvent ?", "Je ne savais pas."),
         N("J'y ai vu mon premier film en couleur. J'en suis sorti{e} ébloui{e}.", "Quel beau souvenir d'enfance.",
           "Et vous avez cherché les couleurs dans la rue en sortant ?", "C'était quel film ?", "Je vois."),
         N("Maintenant, c'est une banque. Quelle tristesse.", "Le souvenir, lui, reste intact.",
           "Au moins, la banque fait aussi du cinéma avec ses frais.", "Vous allez au cinéma de Bourgoin, maintenant ?", "C'est dommage.")],
        [N("Mon premier baiser, c'était sur ce pont, là-bas.", "C'est un joli endroit pour un premier baiser.",
           "Le pont s'en souvient encore, il est tout rouge.", "Et qu'est-ce qu'elle est devenue, cette personne ?", "Ah oui."),
         N("On s'est marié{e}s deux ans plus tard. Cinquante ans de mariage, l'an prochain.", "C'est magnifique, toutes mes félicitations.",
           "Cinquante ans ! C'est plus long que mon contrat de taxi.", "Vous allez fêter ça ?", "Bravo."),
         N("Je l'aime toujours autant. Même quand il ronfle.", "C'est ça, le vrai amour.",
           "Le ronflement, c'est la preuve d'amour ultime.", "Quel est votre secret ?", "C'est beau.")],
    ],
    "route": [
        [N("Vous avez vu ce radar, à l'entrée du village ?", "Oui, il faut faire attention aux enfants, ici.",
           "Je l'ai vu, et il m'a vu aussi, je crois.", "Il est là depuis quand ?", "Oui."),
         N("Mon voisin s'est fait flasher trois fois en un mois.", "Il devrait ralentir, c'est plus prudent.",
           "Il fait collection de photos, peut-être.", "Il roulait vite ?", "Ça coûte cher."),
         N("Il dit que le radar est mal réglé. Évidemment.", "C'est plus facile d'accuser le radar.",
           "Le radar, lui, dit que c'est le voisin.", "Vous le croyez ?", "Évidemment.")],
        [N("Ça fait combien de temps que vous êtes chauffeur ?", "Quelques années, et j'aime toujours autant ce métier.",
           "Depuis que je sais tourner un volant.", "Pourquoi vous me demandez ça ?", "Un moment."),
         N("Vous devez en voir, des gens bizarres.", "Surtout des gens charmants, comme vous.",
           "Des gens bizarres ? Vous êtes le premier de la journée.", "Vous avez une histoire de taxi bizarre ?", "Un peu."),
         N("Une fois, un chauffeur m'a raconté qu'il avait transporté une chèvre.", "Il faut de tout pour faire un monde.",
           "La chèvre a laissé un pourboire ?", "Une vraie chèvre ? Pour aller où ?", "Possible.")],
    ],
    "cuisine": [
        [N("Vous connaissez la recette des bugnes ?", "Ce sont de vrais petits bonheurs.",
           "Je connais surtout la recette pour les manger.", "C'est une spécialité d'ici ?", "Un peu."),
         N("C'est pour Mardi gras. Ma grand-mère en faisait des montagnes.", "Ce sont de belles traditions.",
           "Et vous finissiez couvert de sucre glace ?", "Vous en faites encore ?", "Classique."),
         N("Le secret, c'est un zeste de citron et une goutte de rhum.", "Ça doit sentir délicieusement bon.",
           "La goutte de rhum, c'est pour le cuisinier.", "Vous m'écrivez la recette ?", "Noté.")],
    ],
    "sport": [
        [N("Je fais du vélo tous les dimanches, sur les petites routes.", "C'est une belle façon de profiter du coin.",
           "Vous me doublez, des fois, dans les côtes ?", "Vous faites combien de kilomètres ?", "Bonne idée."),
         N("Quatre-vingts kilomètres, avec la côte de Chamont. Elle est terrible.", "Chapeau, c'est un sacré effort.",
           "En descente, c'est déjà terrible pour mon taxi.", "Vous roulez en groupe ?", "Pas mal."),
         N("À l'arrivée, on s'arrête toujours au café. C'est le meilleur moment.", "C'est ça, le vrai plaisir du sport.",
           "Le café, c'est le vrai sport national.", "Vous avez un bon café à me conseiller ?", "Je comprends.")],
    ],
    "vacances": [
        [N("J'ai gagné un voyage au Japon, à la tombola !", "Quelle chance, je suis content pour vous !",
           "À la tombola ? Moi j'ai gagné un saucisson.", "Vous partez quand ?", "Félicitations."),
         N("Je n'ai jamais pris l'avion. J'ai un peu peur.", "Ça va bien se passer, vous verrez, c'est magique.",
           "L'avion, c'est un taxi avec des ailes.", "Qu'est-ce qui vous fait peur ?", "C'est normal."),
         N("Mais je ne vais pas rater ça. Les cerisiers en fleurs, toute ma vie j'en ai rêvé.",
           "Vous allez vivre un rêve, profitez-en.", "Ramenez-moi un cerisier pour le taxi.",
           "Vous allez voir quoi d'autre, là-bas ?", "Bon voyage.")],
    ],
    "animaux": [
        [N("Mon chat a ramené une souris vivante dans la cuisine, hier soir.", "Il voulait vous faire un cadeau.",
           "Il préparait le dîner, c'est gentil.", "Vous l'avez rattrapée ?", "Classique."),
         N("Elle s'est cachée derrière le frigo. On a mis deux heures à l'attraper.", "Quelle soirée, vous avez été patient{e}.",
           "Deux heures ? La souris aurait dû demander un salaire.", "Et le chat, il faisait quoi pendant ce temps ?", "Long."),
         N("Le chat, lui, dormait sur le canapé. Mission accomplie, pour lui.", "Les chats ont leur propre logique.",
           "Il a délégué, c'est un bon manager.", "Il fait souvent ça ?", "Typique.")],
    ],
    "musique": [
        [N("Mon petit-fils m'a fait écouter du rap. Je n'ai rien compris.", "C'est gentil de sa part de partager ça.",
           "Le rap, c'est de la poésie très pressée.", "Ça parlait de quoi ?", "Les générations."),
         N("Mais il y avait un morceau sur sa grand-mère. J'ai pleuré.", "C'est touchant, c'était pour vous ?",
           "Vous voilà fan de rap, alors !", "Il écrit lui-même ?", "C'est émouvant."),
         N("Il veut que je fasse un duo avec lui. À mon âge !", "Ce serait un souvenir magnifique.",
           "Je vous vois déjà en tournée.", "Vous allez accepter ?", "Pourquoi pas.")],
    ],
    "meteo": [
        [N("Ce matin, il y avait du brouillard partout dans la vallée.", "C'est beau, ces matins d'automne.",
           "J'ai cru que les vaches avaient disparu.", "Ça arrive souvent, ici ?", "Oui."),
         N("On ne voyait pas à dix mètres. J'ai roulé au pas.", "Vous avez bien fait d'être prudent{e}.",
           "Au pas ? Comme un cheval de trait.", "Vous conduisez souvent dans ces conditions ?", "Prudent."),
         N("Et à midi, grand soleil. On ne s'ennuie pas avec la météo.", "C'est ce qui fait le charme du coin.",
           "Le temps aussi a ses humeurs.", "Vous préférez quoi, comme temps ?", "C'est vrai.")],
    ],
}
for k, v in PLUS.items():
    FILS.setdefault(k, []).extend(v)

# ---------------------------------------------------------------- débuts et fins
BONJOUR = ["Bonjour ! {dest}, à {dest_commune}, s'il vous plaît.", "Bonsoir… {dest}, {dest_commune}. Merci.",
           "Salut ! Vous m'emmenez à {dest} ? C'est à {dest_commune}.", "{dest}, à {dest_commune}. Et pas de détour, hein !",
           "Bonjour, je vais à {dest}, à {dest_commune}.", "Ah, enfin un taxi ! {dest}, à {dest_commune}, s'il vous plaît."]
FIN = dict(
    bien=["Quelle course agréable ! Gardez la monnaie… et un peu plus.", "J'ai passé un très bon moment. Merci, vraiment !",
          "Ah, si tous les chauffeurs étaient comme vous !", "Merci pour la conversation, ça m'a fait du bien.",
          "Je demanderai votre taxi la prochaine fois !", "Vous avez illuminé ma journée."],
    moyen=["Merci, au revoir.", "Bonne journée.", "Voilà pour vous.", "Merci. À la prochaine.", "C'est bon, gardez la monnaie."],
    mal=["Je ne vous recommanderai pas.", "Enfin arrivé{e}…", "La prochaine fois, je prends le bus.",
         "Quelle course pénible.", "Je vais mettre une étoile, pas plus."])
TROP = ["Laissez-moi respirer un peu, voulez-vous.", "Encore ? On vient de parler.", "Vous êtes bien bavard, vous."]
DERANGE = ["Je préfère le silence, si ça ne vous dérange pas.", "Désolé{e}, je ne suis pas très causant{e}.",
           "Pas maintenant, s'il vous plaît."]
# le joueur ne répond pas à temps
SILENCE = ["Hm.", "…", "Vous ne dites rien ?"]


def main():
    data = dict(version=6, tons=TONS, caracteres=CARACTERES, prenoms=PRENOMS, metiers=METIERS, loisirs=LOISIRS,
                animaux=ANIMAUX, familles=FAMILLES, questions=QUESTIONS, esquive=ESQUIVE, fils=FILS, bonjour=BONJOUR,
                fin=FIN, trop=TROP, derange=DERANGE, silence=SILENCE)
    json.dump(data, open(OUT, "w"), ensure_ascii=False, indent=1)
    n_fils = sum(len(v) for v in FILS.values())
    print("fils", n_fils, "échanges", n_fils * 3, "caractères", len(CARACTERES))


if __name__ == "__main__":
    main()
